version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=smarthome
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      - mongo-compose-network
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=123456
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - ./data:/data/db

networks:
  mongo-compose-network:
    driver: bridge


